name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip requirements
        run: |
          pip install --upgrade pip 'setuptools<65.5.0' wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Run flake8
        run: flake8 bpd stubs tests
        if: ${{ always() }}

      - name: Run black
        run: black --check bpd stubs tests
        if: ${{ always() }}

      - name: Check types
        if: ${{ always() }}
        run: |
          # Shim for this issue: https://github.com/ray-project/ray/issues/14431
          touch `python -c 'import site; print(site.getsitepackages()[0])'`/ray/py.typed
          mypy bpd tests


